### ISSUE TITLE
Issues of the First Play test/ Part 1 of Mission/ From tester Frexax

### ISSUE THREAD

**Issue by Frexax** [29j2003/Arma-3-HunterOne2023Remake#1]
1 typ der an der Tür steht kann falschherum schauen
 
2 Intro Info Text sollte mehr nach links

3 Der "Get your gear..." Task sollte eine Sekunde früher beenden

4 Die CSAT KI sollte man etwas langsamer machen, insbesondere der Mech.

5 Eine Kurzbeschreibung wie man ein Heli nutzt während man den Waffencheck macht währe nicht schlecht 

6  ^ zu oberen Punkt weiteren Tipp der angezeigt wird wenn der Spieler das Kampfgebiet erreicht, wo erklärt wird wie das KI ziehen und so funktioniert, was man für Raketen hat etc.

7 Die Anti-Air schießt zu schnell, den Nachlade Prozess langsamer machen.

8 Das Deltadead Ende hat zwar getriggert, hat aber nicht die Informationen angezeigt die es tun sollte (kann daran liegen, das es DELTADEAD war und nicht DeltaDead wie eig. in der description.ext Klassifiziert wurde, aber noch Unkown)

9 Mech. Infanterie sollte stehen, da die sonst zu schlecht erkennbar sind und allg. zu langsam sind.

10 Das sceneEVAC.sqf Skript spielt die sideChat Nachrichten zu früh ab, wahrscheinlich funktioniert das mit den Variablen nicht so wie gewollt, oder wenn schon, sind die Variablen schon zu früh aktiv.

**Comment by 29j2003** [comment]
Mostly fixed, just missing the advanced hints.
