### ISSUE TITLE
Issues of the First Play test/ Part 2 of Mission/ From tester Frexax

### ISSUE THREAD

**Issue by Frexax** [29j2003/Arma-3-HunterOne2023Remake#2]
1 LiveFeed vllt. etwas größer machen und mehr nach unten

2 Nomad Squad weiter nach hinten packen, damit der Spieler auch noch eine Chance hat zu Aufzumunitionieren

3 NomadDead Ende hat zwar wie DeltaDead getriggert, aber nicht die richtige Information angezeigt

4 Infanterie Zerstören Task vllt. doch anzeigen, da sonst der Spieler verwirrt seien könnte (einfach über die Stadt packen und gut ist)

5 Nomad Squad AI Rennt nachdem zweiten Waypoint weg

6 AAF Squad Anzahl die überleben können bevor der Task fertig ist auf min. 4 packen

7 Das Ende triggert zu schnell (direkt nach Mission Complete)

**Comment by 29j2003** [comment]
Fixed.
